export default {
  // 用户数据
  userInfo: {},
  // 用户选择的经纬度
  lnglat: {
    lng: 119.204332,
    lat: 26.06473
  },
  // 寻物信息
  lostContent: [],
  // 失物信息
  foundContent: [],
  // 寻物-学生卡信息
  lost_card_content: [],
  // 寻物-普通用品信息
  lost_common_content: [],
  // 寻物-贵重物品信息
  lost_value_content: [],
  // 失物-学生卡信息
  found_card_content: [],
  // 失物-普通用品信息
  found_common_content: [],
  // 失物-贵重物品信息
  found_value_content: [],
  // 记录用户查看的物品信息
  selected_goods: {},
  // 自己发布过的寻物启事
  userLostContent: [],
  // 自己发布过的失物招领
  userFoundContent: [],
  // 其他用户发布过的寻物启事
  otheruserLostContent: [],
  // 其他用户发布过的失物招领
  otheruserFoundContent: [],
  // 记录用户查看的失物物品信息
  selected_found_goods: {},
  // 记录用户查看的寻物物品信息
  selected_lost_goods: {},
  // 其他用户名
  otherusername: '',
  // 记录搜索的物品
  searchContent: [],
}
